---
abstract: 'Object-oriented interface for inspecting or acting upon upper scope frames.'
author:
  - 'Vincent Pit <perl@profvince.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Scalar::Util: 0
  Scope::Upper: 0.21
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scope-Context
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 0
  Scope::Upper: 0.21
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Scope-Context
  homepage: http://search.cpan.org/dist/Scope-Context/
  license: http://dev.perl.org/licenses/
  repository: http://git.profvince.com/?p=perl%2Fmodules%2FScope-Context.git
version: 0.02
